### ISSUE TITLE
Training on custom datasets

### ISSUE THREAD

**Issue by HalvesChen** [moothes/A2S-v2#11]
Hi, thanks for your ammazing work! I want to deploy this method to custom dataset, could you provide some tips?

**Comment by moothes** [comment]
Thanks for your attention!
I am not sure you want to re-train or deploy on your own data? 
I think you need to modify line 173-195 in data.py, where subset=='e' means the list of testing sets, and the else condition defines the training sets.
After that, you may change your data structure as provided in our data link.
I think it should work.

**Comment by HalvesChen** [comment]
Thank you for your reply! The depth range in the RGBD dataset confuses me, what do I need to do with the depth I've captured if I want to re-train? Normalize to 0-255？

**Comment by moothes** [comment]
In fact, the depth data used in our paper comes from existing RGB-D SOD datasets. More details can be found in their papers.
I think this may not be a big problem as long as the same preprocessing methods are used for all depth data.

**Comment by HalvesChen** [comment]
Thanks 👍
