### ISSUE TITLE
损失与论文形式有差异

### ISSUE THREAD

**Issue by lartpang** [moothes/A2S-v2#2]
很有趣的工作，但是代码似乎需要进行调整，损失函数、变量名称与论文中并不对应，反而为阅读带来了困难。

https://github.com/moothes/A2S-v2/blob/6108a48300b713dd2830d8b54d462d75fb0ac3eb/methods/a2s/loss.py#L18-L54

如果我没有理解错误：
- 这里的rgb对应的是论文中的 $\alpha$ ？
- 这里对应的是论文中提到的 btm 损失？
- 而且这里在计算 btm 的时候，数据被缩小到原始的 0.25 倍的原因是什么呢？论文对此似乎并未提及。

https://github.com/moothes/A2S-v2/blob/6108a48300b713dd2830d8b54d462d75fb0ac3eb/methods/a2s/loss.py#L56-L62

而这里应该对应的是论文中的 csd 损失吧？

但是论文中，csd并没有这里的`pow(0.5, mul)`。

**Comment by moothes** [comment]
您好！感谢您对我们工作的关注。
抱歉，由于当前代码是我们实验时的设置，所以与论文中存在一定差异。我们会尽快根据论文中的定义对应修改变量名称。
(1) rgb是Alpha；
(2) 您所提到的部分和对应的损失是一致的；
(3) 0.25主要是为了减少显存占用，避免out of memory；
(4) pow(0.5, mul)的主要目的是保持该项loss为正数，它与网络的训练过程无关，我们后续会加注释说明。

**Comment by lartpang** [comment]
感谢您的解释。
