### ISSUE TITLE
关于表6实验的一些疑惑

### ISSUE THREAD

**Issue by lartpang** [moothes/A2S-v2#4]
最近正在研读您的工作。

关于表6的实验细节有一些疑惑。

![image](https://user-images.githubusercontent.com/26847524/227515606-a8abc234-f221-4094-9a50-9cab6a703cc3.png)

- 使用的训练集是什么？
- 性能评估使用的测试集是什么？
- MC、DSR、RBD这些方案的训练指代的是什么？
- Ours的before training指的是第一阶段训练之前的激活图经过crf处理后的性能么？
- Ours的after training指的是第一阶段训练后激活图进过crf处理后的性能么？

**Comment by lartpang** [comment]
@moothes 

感谢您的回复，我对无监督SOD任务了解并不深入，可能对于一些实验细节设置不是很清楚。

前面问题中的大部分已经了解。

但是还有一些新的疑惑：

> 我们发现经过预训练的网络可以感知到图像中部分有判别性的区域，因此我们直接使用其生成的激活图作为伪标签。

- 对于这里提到的本文的“预训练”机制，指的是论文中提到的第一阶段么？即通过提出的三个真值无关的损失（csd、btm和ms）来优化伪标签生成模型？
- 这里提到的激活图就是指代第一阶段模型最终生成的单通道图像吧？

> 我们的方法也可以采用现有方法的设计，即利用传统方法得到伪标签，用来指导网络训练，对应的结果就是MC、DSR和RBD的After training结果（经过CRF）。

这里“指导网络训练”指的是使用这些初始伪标签来监督本文的第二阶段的训练么，即“After Training”训练的是第一阶段还是第二阶段呢？

- 如果指代第一阶段的训练：
    - 这里Ours的“Before”和“After”实际上表示的就是第一阶段在模型通过自我约束训练前后的性能对比吧（当然，这里训练后还加了CRF）？
    - 表中基于MC、DSR和RBD获得的初始标签，又是如何监督本文第一阶段的模型呢？是在三个损失的基础上额外引入了真值相关的损失么？
- 如果指代第二阶段的训练：
    - 这里的初始伪标签直接作为第二阶段标签的时候，是不是也得使用CRF呢？

**Comment by moothes** [comment]
首先解释一下，我们的方法主要是针对第一阶段，因此大部分的消融实验都是针对第一阶段的。
- 预训练是指backbone的pre-training，是在ImageNet上进行的，例如原始的ResNet50或MoCo v2。
- 激活图是第一阶段模型最终生成的单通道图像

> 这里Ours的“Before”和“After”实际上表示的就是第一阶段在模型通过自我约束训练前后的性能对比吧（当然，这里训练后还加了CRF）？
表中基于MC、DSR和RBD获得的初始标签，又是如何监督本文第一阶段的模型呢？是在三个损失的基础上额外引入了真值相关的损失么？

第一句话的理解应该是正确的。
对于第二句话，可以参考文中Fig2里面的Noisy label G。在我们的实现中，G是通过网络生成的单通道图像二值化得到的噪声标签，可以将其替换成MC、DSR和RBD等某个传统方法得到的噪声标签，用于网络训练。值得注意的是，在我们的消融实验中，如果使用我们的方式，每张图像的标签在训练过程中是不断优化的；如果使用传统方法的结果，每张图像的标签在训练过程中是固定的。我们认为，这也是我们的方法能够在训练后得到更好伪标签的原因之一。

**Comment by lartpang** [comment]
@moothes 
感谢您的回复。按照我的阅读后的理解，第一阶段应该是完全不依赖标签的训练过程吧？那这里是如何使用这些标签的呢？

**Comment by moothes** [comment]
这是个好问题。
其实这里是个理解方式的区别。针对文中的公式3，文中说明了我们省略了伪标签G，在这里我详细说明一下。
我们的伪标签G是激活图经过0.5阈值后得到的二值化图像。公式3中拉大每个像素到0.5的距离，等价于拉近每个像素与其伪标签G的距离（具体的距离计算公式可能有区别）。
如果从拉大到0.5的距离来看，我们是不依赖标签的，或者说伪标签就是根据每个像素自身预测值得到的。
如果从拉近每个像素与伪标签的距离来看，我们的方法是用了一种隐式的方法利用到了伪标签。

无监督显著性的一个最重要的问题是，如何定位到图像中的显著性信息。无论是基于传统方法还是我们的激活图，都需要首先通过某种方式让网络从这些信息中得到初始的显著性信息。因此，对于目前的USOD方法，理论上都是需要伪标签的。

**Comment by lartpang** [comment]
@moothes 
感谢您的解答！
所以这里实际上，如果引入额外生成的伪标签的话，它们**仅仅会参与Lcsd损失的监督过程**喽？

**Comment by moothes** [comment]
如果是传统方法生成的伪标签，是只使用Lcsd损失的。
如果是我们使用的激活图，会在Lbtm中用到动态的边缘信息。

**Comment by lartpang** [comment]
@moothes 
感谢您的解答，这些细节问题在论文中补充出来，或许有助于读者的理解:>
